export const RoleEnum = Object.freeze({
    ADMIN:       Object.freeze({ key: "ADMIN", value: 1, displayName: "Admin" }),
    SCADA_SE:    Object.freeze({ key: "SCADA_SE", value: 2, displayName: "SCADA SE" }),
    SMD_XEN:     Object.freeze({ key: "SMD_XEN", value: 3, displayName: "SMD XEN" }),
    SMD_SDE:     Object.freeze({ key: "SMD_SDE", value: 4, displayName: "SMD SDE" }),
    SMD_AE:      Object.freeze({ key: "SMD_AE", value: 5, displayName: "SMD AE" }),
    SMD_SAE:     Object.freeze({ key: "SMD_SAE", value: 6, displayName: "SMD SAE" }),
    NOD_XEN:     Object.freeze({ key: "NOD_XEN", value: 7, displayName: "NOD XEN" }),
    NOD_SDE:     Object.freeze({ key: "NOD_SDE", value: 8, displayName: "NOD SDE" }),
    NOD_AE:      Object.freeze({ key: "NOD_AE", value: 9, displayName: "NOD AE" }),
    NOD_SAE:     Object.freeze({ key: "NOD_SAE", value: 10, displayName: "NOD SAE" }),
    CONTRACTOR:  Object.freeze({ key: "CONTRACTOR", value: 11, displayName: "Contractor" }),
    IMD:         Object.freeze({ key: "IMD", value: 12, displayName: "IMD" }),
    EMD:         Object.freeze({ key: "EMD", value: 13, displayName: "EMD" }),
    CNST_XEN:    Object.freeze({ key: "CNST_XEN", value: 14, displayName: "CNST XEN" }),
    CNST_SDE:    Object.freeze({ key: "CNST_SDE", value: 15, displayName: "CNST SDE" }),
    CNST_AE:     Object.freeze({ key: "CNST_AE", value: 16, displayName: "CNST AE" }),
});
